Vagrant.configure(2) do |config|

  # ------------------------------ vm1 ------------------------------
  # ssh vagrant@127.0.0.1 -p 2001 -o StrictHostKeyChecking=no -i .vagrant/machines/vm1/docker/private_key
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = 'vm1'
    vm1.vm.network :private_network, type: "dhcp", docker_network__internal: true
    vm1.vm.network :private_network, ip: "10.10.10.11", netmask: "16"

    vm1.vm.network :forwarded_port, id: "ssh", host: 2001, guest: 22
    vm1.vm.network :forwarded_port, id: "nginx", host: 8061, guest: 80
    vm1.vm.network :forwarded_port, id: "consul", host: 8501, guest: 8500

    # Custom configuration for docker
    vm1.vm.provider "docker" do |docker, override|
      # docker doesnt use boxes
      override.vm.box = nil

      # this is where your Dockerfile lives
      docker.build_dir = "."

      docker.name = "vm1"

      # Make sure it sets up ssh with the Dockerfile
      override.ssh.insert_key = true
      docker.has_ssh = true

      # Configure Docker to allow access to more resources
      docker.privileged = true
    end

    # Install Docker Engine and run containers
    vm1.vm.provision :docker do |provision|
      # provision.pull_images "postgres:alpine"
      # provision.run "postgres:alpine", args: "-d -p 5432:5432 -e POSTGRES_PASSWORD=postgres"
      provision.pull_images "nginx"
      provision.run "nginx", args: "-d -p 80:80"
    end

    # Sync folder between host and guest
    vm1.vm.synced_folder "./synced_vm1", "/home/vagrant/synced_folder"

    # You first need to install a vagrant plugin on your machine: 'vagrant plugin install vagrant-docker-compose'
    # CAUTION: the repo is not maintained since Oct 2019 and tries to download an old docker-compose version by default which DOES NOT EXIST anymore
    # that's why we have to provide a version number explicitly.
    # We can also specify a docker-compose file which should be run on startup
    vm1.vm.provision :docker_compose, compose_version: "v2.2.3", yml: "/home/vagrant/synced_folder/docker-compose.yml", run: "always"

  end

  # ------------------------------ vm2 ------------------------------
  # ssh vagrant@127.0.0.1 -p 2002 -o StrictHostKeyChecking=no -i .vagrant/machines/vm2/docker/private_key
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = 'vm2'
    vm2.vm.network :private_network, type: "dhcp", docker_network__internal: true
    vm2.vm.network :private_network, ip: "10.10.10.12", netmask: "16"

    vm2.vm.network :forwarded_port, id: "ssh", host: 2002, guest: 22
    vm2.vm.network :forwarded_port, id: "nginx", host: 8062, guest: 80
    vm2.vm.network :forwarded_port, id: "consul", host: 8502, guest: 8500

    # Custom configuration for docker
    vm2.vm.provider "docker" do |docker, override|
      # docker doesnt use boxes
      override.vm.box = nil

      # this is where your Dockerfile lives
      docker.build_dir = "."

      docker.name = "vm2"

      # Make sure it sets up ssh with the Dockerfile
      override.ssh.insert_key = true
      docker.has_ssh = true

      # Configure Docker to allow access to more resources
      docker.privileged = true
    end

    # Install Docker Engine and run containers
    vm2.vm.provision :docker do |provision|
      provision.pull_images "nginx"
      provision.run "nginx", args: "-d -p 80:80"
    end

    # Sync folder between host and guest
    vm2.vm.synced_folder "./synced_vm2", "/home/vagrant/synced_folder"

    # You first need to install a vagrant plugin on your machine: 'vagrant plugin install vagrant-docker-compose'
    # CAUTION: the repo is not maintained since Oct 2019 and tries to download an old docker-compose version by default which DOES NOT EXIST anymore
    # that's why we have to provide a version number
    # We can also specify a docker-compose file which should be run on startup
    vm2.vm.provision :docker_compose, compose_version: "v2.2.3", yml: "/home/vagrant/synced_folder/docker-compose.yml", run: "always"

  end

end
    

    